server:
  port: 8125
spring:
  redis:
    host:
    database: 0 # 使用0号池
    port: 6379
    password:
  elasticsearch:
    uris:
    username: root
    password:
    connection-timeout: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 当数据库字段使用_连接时这里配置成true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
  mapper-locations: classpath*:/mapper/**/*.xml # 配置xml文件位置，这里是和@mapperscan注解的作用是不同的，后者是指定dao的位置
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
antares:
  thread: # 线程池配置
    coreSize: 32
    maxSize: 32
    keepAliveTime: 10